server:
   port: 8010
spring:
   application:
      name: microservice-simple-consumer-movie
   jap:
      generate-ddl: false
      show-sql: true
      hibernate:
         ddl-auto: none
   datasource:
         url: jdbc:mysql://127.0.0.1:3306/garyh?characterEncoding=UTF-8
         username: root
         password: admin
         driverClassName: com.mysql.jdbc.Driver
         max-active: 20
         max-idle: 8
         min-idle: 8
         initial-size: 10
logging:
   level:
      root: INFO
      org.hibernate: INFO
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
      com.garyhu.feign.StudentFeignClient: DEBUG
#配置下/info接口的信息
info:
   app:
      name: @project.artifactId@
      encoding: @project.build.sourceEncoding@
      java:
         source: @java.version@
         target: @java.version@
eureka:
   client:
      serviceUrl:
         # 注册到集群上，也可以只注册一个，因为多个Eureka Server之间的数据会互相同步
         defaultZone: http://garyhu:pass123@peer1:8761/eureka/,http://garyhu:pass123@peer2:8762/eureka/
      instance:
         prefer-ip-address: true #表示将自己的Ip注册到Eureka Server上
         metadata-map:
            my-metadata: 我自定义的元数据
            name: ll
      # 开启健康检查
      healthcheck:
         enabled: true
# Ribbon配置，该配置是Ribbon脱离了Eureka
#microservice-simple-provider-user:
   #ribbon:
      #listOfServers: localhost:8000,localhost:8001 #指定服务器IP
feign:
   # 压缩
   compression:
      request:
         enabled: true
         mime-types: text/xml,application/xml,application/json     # 支持的媒体类型
         min-request-size: 2048                                   # 设置请求的最小阈值
   # 全局禁用Hystrix
   #hystrix:
      #enabled: false