server:
   port: 8010
spring:
   application:
      name: microservice-simple-consumer-movie
   jap:
      generate-ddl: false
      show-sql: true
      hibernate:
         ddl-auto: none
   datasource:
         url: jdbc:mysql://127.0.0.1:3306/garyh?characterEncoding=UTF-8
         username: root
         password: garyhu
         driverClassName: com.mysql.jdbc.Driver
         max-active: 20
         max-idle: 8
         min-idle: 8
         initial-size: 10
   # 采用消息中间件来收集时，注释该配置
   #zipkin:
      #base-url: http://localhost:9411 # 指定zipkin的地址
   rabbitmq:
      host: localhost
      port: 5672
      username: guest
      passwrod: guest
   sleuth:
      sampler:
         percentage: 1.0   # 指定需采样的请求百分比，默认值是0.1，即10%
   cloud:
      loadbalancer:
         retry:
            enabled: true   # 默认false，即不开启重试 ；true开启重试
   data:
      elasticsearch:
         cluster-nodes: 127.0.0.1:9300
         transport-client:
            client-transport-sniff: false
logging:
   level:
      root: INFO
      org.hibernate: INFO
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
      com.garyhu.feign.StudentFeignClient: DEBUG
      org.springframework.web.servlet.DispatcherServlet: DEBUG
      org.springframework.cloud.sleuth: DEBUG
#配置下/info接口的信息
info:
   app:
      name: @project.artifactId@
      encoding: @project.build.sourceEncoding@
      java:
         source: @java.version@
         target: @java.version@
eureka:
   client:
      registry-fetch--interval-seconds: 30 # 缓存清单的更新时间；默认为30s
      serviceUrl:
         # 注册到集群上，也可以只注册一个，因为多个Eureka Server之间的数据会互相同步
         defaultZone: http://garyhu:pass123@peer1:8761/eureka/,http://garyhu:pass123@peer2:8762/eureka/
      instance:
         lease-renewal-interval-in-seconds: 30    # 定义服务续约任务的调用时间间隔，即心跳；默认为30s
         lease-expiration-duration-in-seconds: 90   # 定义服务失效的时间 ；默认为90s
         prefer-ip-address: true #表示将自己的Ip注册到Eureka Server上
         # 修改端点采用的是相对路径，因为注册中心默认采用HTTP方式访问，如果采用HTTPS时，需要采用绝对路径
         #statusPageUrlPath: https://${eureka.instance.hostname}/info   # 绝对路径
         #healthCheckUrlPath: https://${eureka.instance.hostname}/health   # 绝对路径
         statusPageUrlPath: /appInfo          # 修改原始/info端点
         healthCheckUrlPath: /checkHealth     # 修改原始/health端点
         metadata-map:
            my-metadata: 我自定义的元数据
            name: ll
      # 开启健康检查
      healthcheck:
         enabled: true
# Ribbon配置，该配置是Ribbon脱离了Eureka
#microservice-simple-provider-user:
   #ribbon:
      #listOfServers: localhost:8000,localhost:8001 #指定服务器IP
feign:
   # 压缩
   compression:
      request:
         enabled: true
         mime-types: text/xml,application/xml,application/json     # 支持的媒体类型
         min-request-size: 2048                                   # 设置请求的最小阈值
   # 全局禁用Hystrix
   #hystrix:
      #enabled: false
#一般单独开个项目来开启监控，此处只是演示配置，先注释了
#turbine:
   #appConfig: PersonalProject,microservice-simple-provider-user  # 监控指定的微服务
   #clusterNameExpression: "'default'"
zuul:
   #ignored-services: '*'             # 使用‘*’可忽略所用微服务，只代理下面routes指定的微服务
   ignored-services: microservice-simple-provider-user
   ignoredPatterns: /**/admin/**     # 忽略所有带/admin/的路径
   # 可以指定全局敏感的Header
   sensitive-headers: Cookie,Set-Cookie,Authorization
   # 可以忽略一些Header,这样Header1和Header2就不会传播到其他的微服务中了，默认情况下ignored-headers为空
   #ignored-headers: Header1,Header2
   # 忽略某些header但是又需要使用下游的header时，可进行下面的配置
   #ignoredSecurity-Headers: false
   routes:
      user-route:        # 该配置方式中，user-route只是路由一个名称，可以任意起
         service-id: personalproject
         path: /getStudent
         # 为personalproject指定敏感Header,会覆盖全局的敏感配置
         sensitive-headers: Cookie,Set-Cookie,Authorization
      #personalproject: /getStudent   # 指定代理的微服务 该方式跟user-route配置一样
# sidecar是用来整合异构语言的，此处只是加点配置，最好另外开个微服务项目来整合
#sidecar:
   #port: 8060                                          # Node.js微服务的端口号
   #health-uri: http://localhost:8060/health.json      # Node.js微服务的健康检查URL
PersonalProject:
   ribbon:
      ConnectTimeout: 250   # 连接超时必须小于断路器的超时时间
      ReadTimeout: 1000
      OkToRetryOnAllOperations: true  # 对所有操作请求都进行重试
      MaxAutoRetriesNextServer: 2     # 切换实例的重试次数
      MaxAutoRetries: 1                # 对当前实例的重试次数
hystrix:
   command:
      default:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 10000
